apiVersion: v1
kind: Service
metadata:
  name: soldout
  labels:
    app.kubernetes.io/name: soldout
    {{- include "soldout.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: soldout
  ports:
    - name: http
      port: {{ .Values.soldout.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: notifier
  labels:
    app.kubernetes.io/name: notifier
    {{- include "soldout.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: notifier
  ports:
    - name: metrics
      port: {{ .Values.notifier.port }}
      targetPort: metrics
